backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "src/images"
public_folder: "/images"
collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Homepage"
        delete: false
        file: "src/index.md"
        slug: "{{slug}}"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/njk.njk"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
          - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
          - {label: "Post Feed Heading", name: "postsHeading", widget: "string", default: "Latest posts"}
          - {label: "Archive Link Text", name: "archiveButtonText", widget: "string", default: "See all posts"}
          - {label: "Social Image", name: "socialImage", widget: "image", required: false}
          - {label: "Body", name: "body", widget: "markdown"}
  - name: "generic_pages"
    label: "Generic Pages"
    folder: "src/pages"
    slug: "{{slug}}"
    preview_path: "pages/{{slug}}"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/page.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink Override (Pattern: '/your-slug/index.html')", name: "permalink", widget: "string", required: false}
      - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
      - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
      - {label: "Social Image", name: "socialImage", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "posts"
    label: "Posts"
    folder: "src/posts"
    slug: "{{slug}}"
    preview_path: "posts/{{slug}}"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "SEO Meta Title", name: "metaTitle", widget: "string", required: false}
      - {label: "SEO Meta Description", name: "metaDesc", widget: "string", required: false}
      - {label: "Social Image", name: "socialImage", widget: "image", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", allow_add: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "propagation"
    label: "Plant Propagation"
    folder: "src/propagation"
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Banner Image", name: "bannerImage", widget: "image", allow_multiple: false}
      - { label: "Intro Content", name: "intro", widget: "markdown" }
      - {label: Plant Name, name: plantName, widget: string, hint: "Add the common name of the plant."}
      - {label: Latin Name, name: plantLatinName, widget: string, hint: "Add the latin name of the plant."}
      - label: "Helpful Resources"
        name: "resources"
        widget: "list"
        label_singular: "Helpful Resource"
        collapsed: true
        summary: '{{fields.title}} - {{fields.source}} [{{fields.sourceType}}]'
        fields:
          - {label: Source, name: source, widget: string, hint: "Use the channel name, website name or book author name."}
          - {label: Title, name: title, widget: string}
          - {label: URL, name: url, widget: string}
          - label: "Source Type"
            name: "sourceType"
            widget: "select"
            options: ["Book", "Article", "Video"]
      - {label: "Prop Attempt Section Lead-In", name: "propAttemptLead", widget: "text", required: false}
      - label: "Propagation Attempts"
        name: "propAttempts"
        widget: "list"
        collapsed: true
        label_singular: "Propagation Attempt"
        required: false
        summary: '{{fields.quote}} - {{fields.author.name}}'
        fields:
          - {label: "Attempt Heading", name: "attemptHeading", widget: "string"}
          - {label: "Internal Reference Number", name: "refNumber", widget: "string"}
          - {label: "USDA Zone", name: "usdaZone", widget: "string"}
          - {label: "Approximate Location", name: "ApproximateLocation", widget: "string"}
          - { label: "Attempt Intro Summary", name: "attemptIntro", widget: "markdown" }
          - label: "Propagation Type"
            name: "sourceType"
            widget: "select"
            options: ["Direct Sowing", "Direct Winter Sowing", "Container Winter Sowing", "Grafting", "Rooting Cuttings"]
          - label: "Material Type"
            name: "materialType"
            widget: "select"
            options: ["Purchased Seeds", "Saved Seeds", "Purchased Cuttings", "Free Cuttings"]
          - {label: "Source Name", name: "sourceName", widget: "string", required: false}
          - {label: "Source Link", name: "sourceLink", widget: "string", required: false}
          - label: "Attempt Updates"
            name: "attemptUpdates"
            widget: "list"
            required: false
            label_singular: "Attempt Update"
            collapsed: true
            summary: '{{fields.updateHeading}} - {{fields.updateDate}}'
            fields:
              - {label: "Update Heading", name: "updateHeading", widget: "string"}
              - label: "Date of Update"
                name: "updateDate"
                widget: "datetime"
                date_format: "MM/DD/YYYY"
                time_format: false
                picker_utc: true
              - label: "Propagation Event"
                name: "propEvent"
                widget: "select"
                required: false
                options: ["Seeds Sown", "Cuttings Taken", "Seeds Germinated", "First True Leaves", "Transplanted Outside", "Potted Up"]
              - { label: "Update Summary", name: "updateSummary", widget: "markdown" }
              - label: "Images"
                name: "imageGroup"
                widget: "list"
                required: false
                collapsed: true
                label_singular: "Image"
                fields:
                  - label: "Image"
                    name: "imageObject"
                    widget: "object"
                    fields:
                      - {label: "Image", name: "src", widget: "image"}
                      - {label: "Alt Text", name: "alt", widget: "string", required: false}
                      - {label: "Title", name: "title", widget: "string", required: false}
      - { label: 'Post Summary', name: 'postSummary', widget: 'markdown' }
  - label: "Globals"
    name: "globals"
    files:
      - label: "Site Data"
        name: "site_data"
        delete: false
        file: "src/_data/site.json"
        fields:
          - {label: "Site Name", name: "name", widget: "string"}
          - {label: "Site Url", name: "url", widget: "string"}
          - {label: "Author Name", name: "authorName", widget: "string"}
          - {label: "Author Email Address", name: "authorEmail", widget: "string"}
          - {label: "Author Twitter Handle", name: "authorHandle", widget: "string", required: false}
          - {label: "Footer Short Description", name: "shortDesc", widget: "string"}
          - {label: "Maximum Posts Per Page", name: "maxPostsPerPage", widget: "number", default: 5}
          - {label: "Show Theme Credit", name: "showThemeCredit", widget: "boolean", default: true}
          - {label: "Enable Third Party Comments Area", name: "enableThirdPartyComments", widget: "boolean", default: false}
          - {label: "Payment Pointer (Web Monetization: https://bit.ly/2kTRI1b)", name: "paymentPointer", widget: "string"}
          - {label: "Favicon path (EG: /images/favicon.png)", name: "faviconPath", widget: "string"}
      - label: "Navigation"
        name: "nav"
        delete: false
        file: "src/_data/navigation.json"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - {label: "Text", name: "text", widget: "string"}
              - {label: "Url", name: "url", widget: "string"}
              - {label: "Is url to external site?", name: "external", widget: "boolean", required: false}
      - label: "Theme Settings"
        name: "theme"
        delete: false
        file: "src/_data/tokens.json"
        fields:
          - label: "Size Scale"
            name: "size-scale"
            widget: "object"
            fields: 
              - {label: "Base Size", name: "base", widget: "string", default: "1rem"}
              - {label: "Ratio: 300", name: "300", widget: "string", default: "0.8rem"}
              - {label: "Ratio: 500", name: "500", widget: "string", default: "1.25rem"}
              - {label: "Ratio: 600", name: "600", widget: "string", default: "1.56rem"}
              - {label: "Ratio: 700", name: "700", widget: "string", default: "1.95rem"}
              - {label: "Ratio: 800", name: "800", widget: "string", default: "2.44rem"}
              - {label: "Ratio: 900", name: "900", widget: "string", default: "3.05rem"}
              - {label: "Max Size", name: "max", widget: "string", default: "4rem"}
          - label: "Colors"
            name: "colors"
            widget: "object"
            fields: 
              - {label: "Primary", name: "primary", widget: "string", default: "hsl(208, 57%, 21%)"}
              - {label: "Primary Shade (darker)", name: "primary-shade", widget: "string", default: "hsl(208, 56%, 14%)"}
              - {label: "Primary Glare (lighter)", name: "primary-glare", widget: "string", default: "hsl(207, 57%, 31%)"}
              - {label: "Highlight", name: "highlight", widget: "string", default: "hsl(42, 98%, 77%)"}
              - {label: "Light", name: "light", widget: "string", default: "hsl(0, 0%, 100%)"}
              - {label: "Mid", name: "mid", widget: "string", default: "hsl(0, 0%, 80%)"}
              - {label: "Dark", name: "dark", widget: "string", default: "hsl(0, 0%, 20%)"}
              - {label: "Slate", name: "slate", widget: "string", default: "hsl(0, 0%, 25%)"}
          - label: "Fonts"
            name: "fonts"
            widget: "hidden"
            default: { "base": "\"-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'\"", "serif": "\"'Lora', serif\""}
  # Below is the dev section of the config file
  - name: "dev"
    label: "Component Dev"
    folder: "src/dev"
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    create: true
    fields:
      - {label: "Heading Text", name: "cardHeading", widget: "string"}
      - { label: "Card Content", name: "cardContent", widget: "markdown" }
      - name: "starRating"
        label: "Star Rating"
        widget: "select"
        required: false
        options:
          - { label: "0.5 Stars", value: "0.5"}
          - { label: "1 Stars", value: "1.0"}
          - { label: "1.5 Stars", value: "1.5"}
          - { label: "2 Stars", value: "2.0"}
          - { label: "2.5 Stars", value: "2.5"}
          - { label: "3 Stars", value: "3.0"}
          - { label: "3.5 Stars", value: "3.5"}
          - { label: "4 Stars", value: "4.0"}
          - { label: "4.5 Stars", value: "4.5"}
          - { label: "5 Stars", value: "5"}
      - label: "Image"
        name: "cardImage"
        widget: "object"
        required: false
        fields:
          - {label: "Image", name: "src", widget: "image"}
          - {label: "Alt Text", name: "alt", widget: "string", required: false}
          - {label: "Title", name: "title", widget: "string", required: false}
      - label: "Button"
        name: "cardButton"
        widget: "object"
        required: false
        fields:
          - {label: "Link URL", name: "url", widget: "string"}
          - {label: "Button Text", name: "buttonText", widget: "string"}
  # Above is the dev section of the config file
